{
  config,
  extendedLib,
  lib,
  options,
  pkgs,
  ...
}:

with extendedLib;
let
  cfg = config.modules.editors.emacs;
  escapeElispString =
    s:
    lib.replaceStrings
      [
        "\\"
        "\""
        "\n"
      ]
      [
        "\\\\"
        "\\\""
        "\\n"
      ]
      s;
in
{
  options.modules.editors.emacs = with types; {
    enable = mkBoolOpt false;
    user = mkOption {
      type = types.nullOr (
        types.submodule {
          options = {
            fullName = mkOption {
              type = types.str;
              description = "Value for Emacs `user-full-name`.";
            };
            mailAddress = mkOption {
              type = types.str;
              description = "Value for Emacs `user-mail-address`.";
            };
          };
        }
      );
      default = null;
      description = ''
        Identity passed to Emacs as `user-full-name` and `user-mail-address`
        via `~/.config/doom/user.el`. When null, that file is not installed.
      '';
    };
  };

  config = mkIf cfg.enable (
    mkMerge [
      {
        home.packages = with pkgs; [ ];

        home.configFile."doom" = {
          source = ../../config/doom;
          recursive = true;
        };

        home.sessionVariables = {
          DOOM = "${config.home.configDir}/emacs/bin";
          EDITOR = "emacs";
        };

        home.sessionPath = [
          "$DOOM"
        ];
      }

      (mkIf (cfg.user != null) {
        home.configFile."doom/user.el".source = pkgs.writeText "doom-user.el" ''
          ;;; Generated by Home Manager — do not edit.
          (setq user-full-name "${escapeElispString cfg.user.fullName}"
                user-mail-address "${escapeElispString cfg.user.mailAddress}")
        '';
      })
    ]
  );
}
